language: node_js
before_install:
  - ./travis-install-sysconfcpus
cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
script: 
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 yarn build
before_deploy:
  - zip -r potential-fiesta-production-$(git rev-parse HEAD).zip dist server.js package.json
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: eu-west-1
  app: potential-fiesta
  env: potential-fiesta-production
  zip_file: potential-fiesta-production-$(git rev-parse HEAD).zip
  bucket_name: elasticbeanstalk-eu-west-1-836966196605
  on:
    branch: master