language: node_js
before_install:
  - ./travis-install-sysconfcpus
cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
script: 
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 yarn build
before_deploy:
  - ./set-env
  - echo "ZIP_FILE = ${ZIP_FILE}"
  - echo "AWS_ENV = ${AWS_ENV}"
  - zip -r $ZIP_FILE dist server.js package.json
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: eu-west-1
  app: potential-fiesta
  env: $AWS_ENV
  zip_file: $ZIP_FILE
  bucket_name: elasticbeanstalk-eu-west-1-836966196605
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^staging|production$
