#!/bin/bash

echo "Setting up environment variables"
if [[ $TRAVIS_BRANCH == 'staging' ]]; then
    AWS_ENV=potential-fiesta-staging
    ZIP_FILE=potential-fiesta-staging-$(git rev-parse HEAD).zip
elif [[ $TRAVIS_BRANCH == 'master' ]]; then
    AWS_ENV=potential-fiesta-production
    ZIP_FILE=potential-fiesta-production-$(git rev-parse HEAD).zip
else
    exit 0
fi

echo "ENV=${AWS_ENV}"
echo "ZIP_FILE=${ZIP_FILE}"